In [1]:
import pandas as pd
import numpy as np
import sklearn

# reading in the csv of everyone who took the diabetes survey
diabetics = pd.read_csv('~/Downloads/NHANES data1/P_DIQ_2017_2020.csv')

print(diabetics)

           SEQN  DIQ010  DID040  DIQ160  DIQ180  DIQ050  DID060  DIQ060U  \
0      109263.0     2.0     NaN     NaN     NaN     NaN     NaN      NaN
1      109264.0     2.0     NaN     2.0     2.0     NaN     NaN      NaN
2      109265.0     2.0     NaN     NaN     NaN     NaN     NaN      NaN
3      109266.0     2.0     NaN     1.0     1.0     NaN     NaN      NaN
4      109267.0     2.0     NaN     2.0     2.0     NaN     NaN      NaN
...         ...     ...     ...     ...     ...     ...     ...      ...
14981  124818.0     2.0     NaN     2.0     2.0     NaN     NaN      NaN
14982  124819.0     2.0     NaN     NaN     NaN     NaN     NaN      NaN
14983  124820.0     2.0     NaN     NaN     NaN     NaN     NaN      NaN
14984  124821.0     3.0     NaN     NaN     1.0     NaN     NaN      NaN
14985  124822.0     2.0     NaN     1.0     1.0     NaN     NaN      NaN

       DIQ070  DIQ230  ...  DIQ300D  DID310S  DID310D  DID320  DID330  DID341  \
0         NaN     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN
1         NaN     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN
2         NaN     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN
3         2.0     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN
4         NaN     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN
...       ...     ...  ...      ...      ...      ...     ...     ...     ...
14981     NaN     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN
14982     NaN     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN
14983     NaN     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN
14984     2.0     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN
14985     2.0     NaN  ...      NaN      NaN      NaN     NaN     NaN     NaN

       DID350  DIQ350U  DIQ360  DIQ080
0         NaN      NaN     NaN     NaN
1         NaN      NaN     NaN     NaN
2         NaN      NaN     NaN     NaN
3         NaN      NaN     NaN     NaN
4         NaN      NaN     NaN     NaN
...       ...      ...     ...     ...
14981     NaN      NaN     NaN     NaN
14982     NaN      NaN     NaN     NaN
14983     NaN      NaN     NaN     NaN
14984     NaN      NaN     NaN     NaN
14985     NaN      NaN     NaN     NaN

[14986 rows x 28 columns]

In [2]:
# reading in whoever took the NHANES demographics survey
demographics = pd.read_csv('~/Downloads/NHANES data1/P_DEMO_2017_2020.csv')
print(demographics)

           SEQN  SDDSRVYR  RIDSTATR  RIAGENDR  RIDAGEYR  RIDAGEMN  RIDRETH1  \
0      109263.0      66.0       2.0       1.0       2.0       NaN       5.0
1      109264.0      66.0       2.0       2.0      13.0       NaN       1.0
2      109265.0      66.0       2.0       1.0       2.0       NaN       3.0
3      109266.0      66.0       2.0       2.0      29.0       NaN       5.0
4      109267.0      66.0       1.0       2.0      21.0       NaN       2.0
...         ...       ...       ...       ...       ...       ...       ...
15555  124818.0      66.0       2.0       1.0      40.0       NaN       4.0
15556  124819.0      66.0       2.0       1.0       2.0       NaN       4.0
15557  124820.0      66.0       2.0       2.0       7.0       NaN       3.0
15558  124821.0      66.0       2.0       1.0      63.0       NaN       4.0
15559  124822.0      66.0       2.0       1.0      74.0       NaN       2.0

       RIDRETH3  RIDEXMON  DMDBORN4  ...  FIAINTRP  MIALANG  MIAPROXY  \
0           6.0       2.0       1.0  ...       2.0      NaN       NaN
1           1.0       2.0       1.0  ...       2.0      1.0       2.0
2           3.0       2.0       1.0  ...       2.0      NaN       NaN
3           6.0       2.0       2.0  ...       2.0      1.0       2.0
4           2.0       NaN       2.0  ...       2.0      NaN       NaN
...         ...       ...       ...  ...       ...      ...       ...
15555       4.0       1.0       1.0  ...       2.0      1.0       2.0
15556       4.0       2.0       1.0  ...       2.0      NaN       NaN
15557       3.0       2.0       1.0  ...       2.0      NaN       NaN
15558       4.0       1.0       1.0  ...       2.0      1.0       2.0
15559       2.0       2.0       2.0  ...       NaN      2.0       2.0

       MIAINTRP  AIALANGA      WTINTPRP      WTMECPRP  SDMVPSU  SDMVSTRA  \
0           NaN       NaN   7891.762435   8951.815567      3.0     156.0
1           2.0       1.0  11689.747264  12271.157043      1.0     155.0
2           NaN       NaN  16273.825939  16658.764203      1.0     157.0
3           2.0       1.0   7825.646112   8154.968193      2.0     168.0
4           NaN       NaN  26379.991724      0.000000      1.0     156.0
...         ...       ...           ...           ...      ...       ...
15555       2.0       1.0  21586.596728  21666.889837      1.0     166.0
15556       NaN       NaN   1664.919253   1838.169709      2.0     171.0
15557       NaN       NaN  14819.783161  16497.806674      1.0     157.0
15558       2.0       1.0   4666.817952   4853.430230      1.0     158.0
15559       2.0       NaN  14024.476634  15195.796658      1.0     149.0

       INDFMPIR
0          4.66
1          0.83
2          3.06
3          5.00
4          5.00
...         ...
15555      3.82
15556      0.07
15557      1.22
15558      3.71
15559       NaN

[15560 rows x 29 columns]

In [3]:
# this table now has everyone who took the demographic and diabetes surveys with demographic info
diabetics = diabetics.merge(demographics, on = "SEQN", how = "inner")

In [4]:
# this table has everyone who has diabetes
only_dm = diabetics.query("DIQ010 == 1")
print(only_dm)

           SEQN  DIQ010  DID040  DIQ160  DIQ180  DIQ050  DID060  DIQ060U  \
10     109274.0     1.0    54.0     NaN     NaN     1.0     1.0      2.0
11     109275.0     1.0     4.0     NaN     NaN     1.0     2.0      2.0
24     109290.0     1.0    60.0     NaN     NaN     2.0     NaN      NaN
26     109292.0     1.0    55.0     NaN     NaN     2.0     NaN      NaN
31     109298.0     1.0    52.0     NaN     NaN     2.0     NaN      NaN
...         ...     ...     ...     ...     ...     ...     ...      ...
14942  124778.0     1.0    44.0     NaN     NaN     2.0     NaN      NaN
14952  124788.0     1.0    50.0     NaN     NaN     2.0     NaN      NaN
14960  124796.0     1.0    54.0     NaN     NaN     2.0     NaN      NaN
14966  124803.0     1.0    32.0     NaN     NaN     2.0     NaN      NaN
14980  124817.0     1.0    67.0     NaN     NaN     2.0     NaN      NaN

       DIQ070  DIQ230  ...  FIAINTRP  MIALANG  MIAPROXY  MIAINTRP  AIALANGA  \
10        1.0     1.0  ...       2.0      1.0       2.0       2.0       1.0
11        2.0     1.0  ...       2.0      NaN       NaN       NaN       NaN
24        1.0     2.0  ...       2.0      1.0       2.0       2.0       1.0
26        1.0     5.0  ...       2.0      1.0       2.0       2.0       NaN
31        1.0     4.0  ...       2.0      1.0       1.0       2.0       NaN
...       ...     ...  ...       ...      ...       ...       ...       ...
14942     1.0     4.0  ...       2.0      1.0       2.0       2.0       1.0
14952     2.0     5.0  ...       2.0      1.0       2.0       2.0       1.0
14960     1.0     5.0  ...       2.0      1.0       2.0       2.0       1.0
14966     1.0     1.0  ...       2.0      2.0       2.0       2.0       2.0
14980     1.0     5.0  ...       2.0      2.0       2.0       2.0       2.0

           WTINTPRP      WTMECPRP  SDMVPSU  SDMVSTRA  INDFMPIR
10      7227.993241   7801.600218      2.0     167.0      1.20
11     16372.533970  17610.326826      2.0     164.0      3.74
24      3967.693106   4099.841985      1.0     171.0      5.00
26     15941.778001  17463.112885      2.0     150.0      1.60
31      7587.880067   7866.974787      1.0     167.0      1.75
...             ...           ...      ...       ...       ...
14942  13324.280657  13922.135130      1.0     154.0      5.00
14952   3013.473594   3103.475884      1.0     171.0      4.69
14960   4516.585648   4667.864801      1.0     167.0       NaN
14966  24789.078370  24004.883291      1.0     155.0      1.37
14980   7724.092682   8189.572200      2.0     165.0      2.19

[1445 rows x 56 columns]

In [5]:
# this is a table of everyone with diabetic retinopathy
only_dm_ret = only_dm.query("DIQ080 == 1")
print(only_dm_ret)

           SEQN  DIQ010  DID040  DIQ160  DIQ180  DIQ050  DID060  DIQ060U  \
48     109316.0     1.0    58.0     NaN     NaN     2.0     NaN      NaN
102    109373.0     1.0    12.0     NaN     NaN     1.0    18.0      2.0
212    109490.0     1.0    69.0     NaN     NaN     1.0     8.0      2.0
329    109612.0     1.0    60.0     NaN     NaN     2.0     NaN      NaN
354    109638.0     1.0    37.0     NaN     NaN     1.0     5.0      2.0
...         ...     ...     ...     ...     ...     ...     ...      ...
14811  124638.0     1.0    49.0     NaN     NaN     2.0     NaN      NaN
14827  124656.0     1.0    46.0     NaN     NaN     1.0    20.0      2.0
14883  124717.0     1.0    21.0     NaN     NaN     1.0    30.0      2.0
14884  124718.0     1.0    42.0     NaN     NaN     2.0     NaN      NaN
14892  124726.0     1.0   999.0     NaN     NaN     1.0     4.0      2.0

       DIQ070  DIQ230  ...  FIAINTRP  MIALANG  MIAPROXY  MIAINTRP  AIALANGA  \
48        1.0     3.0  ...       2.0      1.0       2.0       2.0       1.0
102       2.0     3.0  ...       2.0      1.0       2.0       2.0       1.0
212       2.0     1.0  ...       2.0      1.0       2.0       2.0       NaN
329       1.0     4.0  ...       NaN      1.0       2.0       2.0       NaN
354       1.0     1.0  ...       2.0      1.0       2.0       2.0       1.0
...       ...     ...  ...       ...      ...       ...       ...       ...
14811     1.0     5.0  ...       2.0      1.0       2.0       2.0       1.0
14827     1.0     4.0  ...       2.0      2.0       2.0       2.0       NaN
14883     2.0     1.0  ...       2.0      1.0       2.0       2.0       1.0
14884     1.0     5.0  ...       2.0      NaN       NaN       NaN       NaN
14892     1.0     3.0  ...       2.0      2.0       2.0       2.0       2.0

            WTINTPRP       WTMECPRP  SDMVPSU  SDMVSTRA  INDFMPIR
48       6119.732139    6448.398885      1.0     150.0      0.07
102     14343.322465   14611.858553      2.0     167.0      1.22
212      4105.767387    4268.063945      2.0     169.0       NaN
329      4219.124104    4280.287645      2.0     151.0       NaN
354    100202.203029  116101.632791      1.0     158.0      3.03
...              ...            ...      ...       ...       ...
14811   86968.490855   91652.121966      2.0     160.0      4.73
14827    3753.780219    4076.321404      2.0     164.0      0.09
14883    7721.079131    7271.786706      2.0     151.0      1.05
14884    7733.690983    8257.430591      2.0     169.0       NaN
14892    5154.404973    5548.580637      1.0     149.0      0.67

[281 rows x 56 columns]

## Demographic distributions for people surveyed that have diabetes:

Here we take the combined table of the diabetes survey joined with demographics and filtered for only those people with diabetes.
Now we will look at each of the significant demographic variables, create plots to break down the distribution of diabetes across each group for each variable, and do hypothesis tests for whether the distribution matches a certain default spread

In [9]:
# this is where we will analyze the demographic variable distributions for everyone with diabetes
ethn_dm_dist = (only_dm.groupby(['RIDRETH3']).size()).reset_index(name = 'dm_counts')
# ethn_dm_dist.rename(columns = {'RIDRETH3': 'Race'})
ethn_dm_dist['dm_props'] = ethn_dm_dist['dm_counts']/sum(ethn_dm_dist['dm_counts'])
total_ethn = (demographics.groupby(['RIDRETH3']).size()).reset_index(name = 'counts')
ethn_dm_dist['total_ethn_counts'] = total_ethn['counts']
ethn_dm_dist['total_ethn_props'] = ethn_dm_dist['total_ethn_counts']/sum(ethn_dm_dist['total_ethn_counts'])
ethn_dm_dist

   RIDRETH3  dm_counts  dm_props  total_ethn_counts  total_ethn_props
0       1.0        187  0.129412               1990          0.127892
1       2.0        145  0.100346               1544          0.099229
2       3.0        470  0.325260               5271          0.338753
3       4.0        418  0.289273               4098          0.263368
4       6.0        150  0.103806               1638          0.105270
5       7.0         75  0.051903               1019          0.065488

In [10]:
# this is where we will analyze the demographic variable distributions for everyone with diabetes
educ_dm_dist = (only_dm.groupby(['DMDEDUC2']).size()).reset_index(name = 'dm_counts')
# ethn_dm_dist.rename(columns = {'RIDRETH3': 'Race'})
educ_dm_dist['dm_props'] = educ_dm_dist['dm_counts']/sum(educ_dm_dist['dm_counts'])
total_educ = (demographics.groupby(['DMDEDUC2']).size()).reset_index(name = 'counts')
educ_dm_dist['total_educ_counts'] = total_educ['counts']
educ_dm_dist['total_educ_props'] = educ_dm_dist['total_educ_counts']/sum(educ_dm_dist['total_educ_counts'])
educ_dm_dist

   DMDEDUC2  dm_counts  dm_props  total_educ_counts  total_educ_props
0       1.0        186  0.130986                719          0.077991
1       2.0        193  0.135915               1041          0.112919
2       3.0        349  0.245775               2225          0.241349
3       4.0        438  0.308451               2975          0.322703
4       5.0        252  0.177465               2257          0.244820
5       9.0          2  0.001408                  2          0.000217

In [13]:
ethn_educ_dm_dist = (only_dm.groupby(['RIDRETH3', 'DMDEDUC2']).size()).reset_index(name = 'dm_counts')
ethn_educ_dm_dist['dm_props'] = ethn_educ_dm_dist['dm_counts']/sum(ethn_educ_dm_dist['dm_counts'])
total_ethn = (demographics.groupby(['RIDRETH3', 'DMDEDUC2']).size()).reset_index(name = 'counts')
ethn_educ_dm_dist['total_counts'] = total_ethn['counts']
ethn_educ_dm_dist['total_props'] = ethn_educ_dm_dist['total_counts']/sum(ethn_educ_dm_dist['total_counts'])
ethn_educ_dm_dist

    RIDRETH3  DMDEDUC2  dm_counts  dm_props  total_counts  total_props
0        1.0       1.0         78  0.054930           279     0.031676
1        1.0       2.0         32  0.022535           178     0.020209
2        1.0       3.0         28  0.019718           244     0.027702
3        1.0       4.0         31  0.021831           261     0.029632
4        1.0       5.0         12  0.008451            93     0.010559
5        1.0       9.0          1  0.000704             2     0.000227
6        2.0       1.0         46  0.032394           195     0.022139
7        2.0       2.0         25  0.017606           141     0.016008
8        2.0       3.0         26  0.018310           192     0.021798
9        2.0       4.0         36  0.025352           256     0.029064
10       2.0       5.0         11  0.007746           151     0.017144
11       3.0       1.0         29  0.020423             5     0.000568
12       3.0       2.0         51  0.035915            81     0.009196
13       3.0       3.0        132  0.092958           287     0.032584
14       3.0       4.0        168  0.118310           835     0.094800
15       3.0       5.0         82  0.057746          1155     0.131131
16       4.0       1.0         15  0.010563           857     0.097298
17       4.0       2.0         66  0.046479             2     0.000227
18       4.0       3.0        120  0.084507            62     0.007039
19       4.0       4.0        145  0.102113           321     0.036444
20       4.0       5.0         63  0.044366           704     0.079927
21       6.0       1.0         16  0.011268           909     0.103202
22       6.0       2.0         12  0.008451           459     0.052112
23       6.0       3.0         20  0.014085             1     0.000114
24       6.0       4.0         25  0.017606             3     0.000341
25       6.0       5.0         76  0.053521            87     0.009877
26       7.0       1.0          2  0.001408            75     0.008515
27       7.0       2.0          7  0.004930           150     0.017030
28       7.0       3.0         23  0.016197           202     0.022934
29       7.0       4.0         33  0.023239           605     0.068688
30       7.0       5.0          8  0.005634             1     0.000114
31       7.0       9.0          1  0.000704            15     0.001703

In [12]:
from scipy.stats import chi2_contingency

idx, *dat = np.reshape(ethn_educ_dm_dist['dm_counts'], (6, -1), order = 'F')
cont_table = pd.DataFrame(dat, columns = idx).T
cont_table
# since there are only a couple of groups with PhDs in the survey, we can't do a contingency table
# so we have to consider excluding them or trying to fill the other groups with NaN

# then we need to add counts by race as a new column
cont_table['total_counts_by_race'] = ethn_dm_dist['dm_counts']

# then we need to add the counts by education level as a new row
cont_table.loc[len(cont_table)] = educ_dm_dist['dm_counts']

# here we run the Chi-square test for distributions
stat, p, dof, expected = chi2_contingency(cont_table)

ValueError: cannot reshape array of size 32 into shape (6,newaxis)

In [ ]:
idx, *dat = np.reshape(ethn_educ_dm_dist['dm_counts'], (6, -1), order = 'F')
cont_table = pd.DataFrame(dat, columns = idx).T
cont_table
# since there are only a couple of groups with PhDs in the survey, we can't do a contingency table
# so we have to consider excluding them or trying to fill the other groups with NaN

# then we need to add counts by race as a new column
cont_table['total_counts_by_race'] = ethn_dm_dist['total_ethn_counts']

# then we need to add the counts by education level as a new row
cont_table.loc[len(cont_table)] = educ_dm_dist['total_educ_counts']

# here we run the Chi-square test for distributions
stat, p, dof, expected = chi2_contingency(cont_table)

### This is where we will look at pre-diabetic patients' racial, educational, other demographic distributions

We will repeat the same process as above doing a Chi-square distribution but this time we already have the distribution of demographics for the entire NHANES surveyed people

In [ ]:
# this is everyone who has prediabetes
only_pre_dm = diabetics.query("DIQ160 == 1")
print(only_pre_dm)

In [ ]:
# this is where we will analyze the demographic variable distributions for everyone with diabetes
ethn_dm_dist = (only_dm.groupby(['RIDRETH3']).size()).reset_index(name = 'dm_counts')
# ethn_dm_dist.rename(columns = {'RIDRETH3': 'Race'})
total_ethn = (demographics.groupby(['RIDRETH3']).size()).reset_index(name = 'counts')
ethn_dm_dist['total_ethn_counts'] = total_ethn['counts']
ethn_dm_dist

In [ ]:
# this is where we will analyze the demographic variable distributions for everyone with diabetes
educ_dm_dist = (only_pre_dm.groupby(['DMDEDUC2']).size()).reset_index(name = 'dm_counts')
# ethn_dm_dist.rename(columns = {'RIDRETH3': 'Race'})
total_educ = (demographics.groupby(['DMDEDUC2']).size()).reset_index(name = 'counts')
educ_dm_dist['total_educ_counts'] = total_educ['counts']
educ_dm_dist

In [ ]:
ethn_educ_dm_dist = (only_pre_dm.groupby(['RIDRETH3', 'DMDEDUC2']).size()).reset_index(name = 'dm_counts')
total_ethn = (demographics.groupby(['RIDRETH3', 'DMDEDUC2']).size()).reset_index(name = 'counts')
ethn_educ_dm_dist['total_counts'] = total_ethn['counts']
ethn_educ_dm_dist

In [ ]:
idx, *dat = np.reshape(ethn_educ_dm_dist['dm_counts'], (6, -1), order = 'F')
cont_table = pd.DataFrame(dat, columns = idx).T
cont_table
# since there are only a couple of groups with PhDs in the survey, we can't do a contingency table
# so we have to consider excluding them or trying to fill the other groups with NaN

# then we need to add counts by race as a new column
cont_table['total_counts_by_race'] = ethn_dm_dist['total_ethn_counts']

# then we need to add the counts by education level as a new row
cont_table.loc[len(cont_table)] = educ_dm_dist['total_educ_counts']

# here we run the Chi-square test for distributions
stat, p, dof, expected = chi2_contingency(cont_table)

## Logistic regression to find factors affecting retinopathy in diabetes patients

This is where we may or may not confirm, or challenge, or update the study where old 2005 NHANES data was used in addition to retinal scans of the diabetic patients.

In [ ]:
from sklearn.model_selection import train_test_split

X = only_dm.loc[:, only_dm.columns != 'DIQ080']
y = only_dm['DIQ080']

# using the train test split function 
X_train, X_test, y_train, y_test = train_test_split(X,y , 
                                   random_state=104,  
                                   test_size=0.30,  
                                   shuffle=True) 

# Import 'LogisticRegression' and create a LogisticRegression object
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()
# Import RFE and select 15 variables
from sklearn.feature_selection import RFE
rfe = RFE(logreg, 15)             
rfe = rfe.fit(X_train, y_train)

In [ ]:
# Let's check the overall accuracy
metrics.accuracy_score(y_pred_final['Converted'], y_pred_final.final_predicted)
TP = confusion2[1,1] # true positive 
TN = confusion2[0,0] # true negatives
FP = confusion2[0,1] # false positives
FN = confusion2[1,0] # false negatives
# Calculate Precision
TP/(TP+FP)
# Calculate Recall
TP/(TP+FN)

In [ ]:
# this is every NHANES prescription ever recorded between 2017 and 2020
prescriptions = pd.read_csv('~/Downloads/P_PRESC_RX_2017_2020.csv')
print(prescriptions)

In [ ]:
# this is all the prescriptions taken by people who took the diabetes survey
prescriptions = prescriptions.merge(diabetics, on = 'SEQN', how = 'inner')

In [ ]:
# these are the prescriptions of everyone with pre-diabetes
prop_pre_dm_rx = prescriptions.query('DIQ160 == 1')
print(prop_pre_dm_rx)

In [ ]:
# these are the prescriptions of everyone with diabetes
prop_dm_rx = prescriptions.query('DIQ010 == 1')
print(prop_dm_rx)

In [ ]:
# these are the prescriptions of everyone with diabetic retinopathy
dm_ret = prescriptions.query('DIQ080 == 1 & DIQ010 == 1')
print(dm_ret)